stages:
  - build
  - test

jar_gateway:
  image: openjdk:11
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - /builds/finbyte/solaris-gateaway/gateway/build/libs/

build_docker_compose:
  image: tmaier/docker-compose:latest
  services:
    - docker:18.09.7-dind
  before_script:
    - docker info
    - docker-compose --version
  stage: test
  script:
    - make test_integration
  after_script:
    - docker-compose -f integration-tests/docker-compose.yml logs >& logs.txt
