# General properties and default values for environment properties
com:
  finbyte:
    solarisgateway:
      uri: "http://localhost:8081"
      prefix : "/solaris/"
      retry:
        count: 2
      auth:
        provider: solaris
        clientid: login-client
        clientsecret: secret
        uaa:
          httpmethod: POST
          baseuri: "http://localhost:8080"
          uri: /oauth/token
          granttype: client_credentials
        solaris:
          httpmethod: POST
          baseuri: "http://localhost:8080"
          uri: /oauth/token
          granttype: client_credentials
        token:
          expire:
            threshold: 10000
      security:
        users:
          - name: paymentUser1
            password: password
            roles: GATEWAY_USER
            enabled: true
          - name: admin
            password: password
            roles: ADMIN
            enabled: true
          - name: oldUser
            password: password
            roles: GATEWAY_USER
            enabled: false
      docker-secret:
        bind-path: "/run/secrets"
        client-id: client-id
        client-secret: client-secret
##################################################################
# Other Properties
##################################################################
server:
  port: 8090
# fix live load not started issue
spring:
  devtools:
    livereload:
      port: 35730

management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,metrics,gateway,info,heapdump,prometheus,env

# rid of spring security in-memory configuration info logs
logging:
  level:
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN