# dev environment properties
##################################################################
# Gateway Properties
##################################################################

##################################################################
# Other Properties
##################################################################
server:
  port: 8090