# General properties and default values for environment properties
com:
  finbyte:
    solarisgateway:
      uri: "http://localhost:8081"
      prefix : "/solaris/"
      retry:
        count: 2
      auth:
        provider: mock
        clientid: login-client
        clientsecret: secret
        httpmethod: POST
        baseuri: "http://localhost:8081"
        uri: /oauth/token
        granttype: client_credentials
        token:
          expire:
            threshold: 10000
      security:
        users:
          - name: paymentUser1
            password: password
            roles: GATEWAY_USER
            enabled: true
          - name: admin
            password: password
            roles: ADMIN
            enabled: true
          - name: oldUser
            password: password
            roles: GATEWAY_USER
            enabled: false
      docker-secret:
        bind-path: "/run/secrets"
        client-id: client-id
        client-secret: client-secret
      logging:
        global: false
        elapsedtime: false
##################################################################
# Other Properties
##################################################################
server:
  port: 8090
# fix live load not started issue
spring:
  devtools:
    livereload:
      port: 35730
  redis:
    host: localhost
    port: 6379


management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,metrics,gateway,info,heapdump,prometheus,env

logging:
  level:
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN
    org.springframework.cloud.gateway: WARN
    org.springframework.boot.autoconfigure.web: WARN
    reactor.netty.http: WARN
    org.springframework.web.reactive: WARN
    org.springframework.http.server.reactive: WARN
