# General properties and default values for environment properties
com:
  finleap:
    solarisgateway:
      uri: "http://localhost:8081"
      prefix : "/solaris/"
      retry:
        count: 2
      auth:
        provider: solaris
        uaa:
          httpmethod: POST
          baseuri: "http://localhost:8080"
          uri: /oauth/token
          clientid: login-client
          clientsecret: secret
          granttype: client_credentials
        solaris:
          httpmethod: POST
          baseuri: "http://localhost:8080"
          uri: /oauth/token
          clientid: login-client
          clientsecret: secret
          granttype: client_credentials
        token:
          expire:
            threshold: 10000

      security:
        users:
          - name: solarisUser1
            password: password
            roles: SOLARIS
            enabled: true
          - name: manager1
            password: password
            roles: MANAGER
            enabled: true
          - name: oldSolarisUser
            password: password
            roles: SOLARIS
            enabled: false

##################################################################
# Other Properties
##################################################################
server:
  port: 8090
# fix live load not started issue
spring:
  devtools:
    livereload:
      port: 35730

management:
  endpoints:
    web:
      exposure:
        include: health,threaddump,metrics,gateway,info,heapdump,prometheus


