version: '3'
services:
  gateway:
    build:
      context: ../gateway
      dockerfile: ./Dockerfile
      args:
        PROVIDER: solaris
        PREFIX: /solaris/
    ports:
      - "8090:8090"
  solaris-mock-server:
    image: $CI_REGISTRY/finbyte/solaris-mock-server/solaris-mock-server:latest
    ports:
      - "8081:8081"
  test-runner:
    build: ""
    ports:
      - "9090:9090"